### ISSUE TITLE
Nome do Projeto

### ISSUE THREAD

**Issue by BeyondMagic** [cerejeiros/mobile#1]
Aqui podemos discutir o nome do projeto.

Poste suas ideias e vote nas melhores que forem dadas.

**Comment by BeyondMagic** [comment]
"entre-linhas"

**Comment by kaioenzo** [comment]
"sossego"

**Comment by NATANGOATOSO** [comment]
healthier

**Comment by Luizaxx** [comment]
habit

**Comment by Luizaxx** [comment]
Habit Petals

**Comment by limonadaquente** [comment]
Bloom

**Comment by Neoprot** [comment]
Navade Petals.
Navade: hábitos em esloveno

**Comment by Luizaxx** [comment]
cherry blossom - ideia de nome que parece idiota, mas estava pensando aqui "blossom" da pra ser usado como verbo de "despertar" "auto desenvolvimento" que vai totalmente ao encontro do nosso aplicativo.

**Comment by Luizaxx** [comment]
melhorando o nome, para ser mais prático, poderia ser Blossom ou só bloom

**Comment by BeyondMagic** [comment]
> Bloom

Nome definido.
