### ISSUE TITLE
Login e contas.

### ISSUE THREAD

**Issue by BeyondMagic** [cerejeiros/mobile#13]
Acredito fielmente que login não deva ser `opt-out`, mas `opt-in`; além de aliviar o banco de dados, isso também não daria a impressão ao usuário que ele esteja sendo inclinado a mais uma vez mandar os dados pessoais para a internet.

Explicação de dos dois termos para quem não possuí familiaridade:
- `opt-out`: ao iniciar o aplicativo pela primeira vez, o usuário vê uma janela pedindo-o para criar uma conta nova ou logar numa antiga.
- `opt-in`: o usuário ao tentar alterar o perfil (conta local) no aplicativo veria uma opção de criar uma conta para salvar os dados na nuvem.

---

Sobre propriedades e valores: https://supabase.com/docs/guides/auth#create-a-publicusers-table

**Comment by kaioenzo** [comment]
Acredito que deveríamos utilizar o `opt-in`. Limitando o acesso do usuários a certas funcionalidades do app, como estatísticas, máximo de tarefas/rotinas criadas e etc.
