### ISSUE TITLE
Conta e perfil de usuário

### ISSUE THREAD

**Issue by kaioenzo** [cerejeiros/mobile#15]
# História de usuário
Eu como usuário do aplicativo, quero poder criar meu perfil, inserir informações básicas, trocar minhas informações e trocar minha foto, para isso é necessário que eu crie uma conta e esteja logado, para que haja a individualidade do meu perfil. Também desejo poder adicionar e visualizar meus amigos no aplicativo.

## Critérios de aceitação
 - [x] Inserção, exclusão e alteração de foto de perfil.
   - [x] A foto deve ser salva em string codificada em base64 no banco de dados.  
 - [x] Deve ser possível adicionar uma biografia.
   - [x] A biografia deve ter no máximo 200 caracteres. 
 - [ ] Deve haver avatares padrões do app, no mínimo 2, um para cada sexo.
 - [ ] Inserção, exclusão e alteração de informações de usuário (senha, email, nome, username, gênero e data de nascimento).
 - [ ] Deve ser possível visualizar e adicionar amigos

**Comment by Neoprot** [comment]
## Critérios de aceitação
 - [ ] Inserção, exclusão e alteração de foto de perfil.
 - [ ] Inserção, exclusão e alteração de informações de usuário (senha, email, nome).

**Comment by kaioenzo** [comment]
Dando início a discussão de arquitetura dos usuários, acredito que essa estrutura inicial básica seja suficiente para representar e relacionar o `Usuario` a outros objetos.
```typescript
type Usuario = {
  id: number;
  nome: string;
  foto?: string;
  bio: string;
  tasks?: Task[ ]
  amigos?: Usuario[ ]
} 
```

**Comment by BeyondMagic** [comment]
A biografia deve ter no mínimo 20 caracteres e máximo, ~150 a 200. Ninguém quer ler uma bibliografia de verdade, é mais curto do que precisa ser.

**Comment by BeyondMagic** [comment]
Eu também discordo de limites, estava [lendo aqui](https://medium.com/ux-school/bad-form-design-first-name-must-be-at-least-4-characters-c882a9c3407f) agora e não vejo motivo algum de forçar o usuário a escrever mais caso queira uma biografia. Não conheço nenhuma plataforma que é usado por milhões de pessoas que faça isso.

Foi falado na última reunião que a biografia podia ser opcional, o que é agora; mas que mantesse o limite de minimo.
