### ISSUE TITLE
Logo em SVG (Scalable Vector Graphics)

### ISSUE THREAD

**Issue by BeyondMagic** [cerejeiros/mobile#19]
Uma parte fundamental do projeto é a logo do projeto.

Nós já temos a paleta e protótipo, vocês podem usar Inkscape or Illustrator para criar ela e exportar em SVG; assim poderemos utilizá-la.

@cerejeiros/design

**Comment by NATANGOATOSO** [comment]
[LOGO SVG.zip](https://github.com/cerejeiros/mobile/files/11360393/LOGO.SVG.zip)

**Comment by kaioenzo** [comment]
@NATANGOATOSO exporte um png para a utilização como [app icon](https://docs.expo.dev/tutorial/configuration/#app-icon)

**Comment by NATANGOATOSO** [comment]
[LOGO_SVG_E_PNG.zip](https://github.com/cerejeiros/mobile/files/11361655/LOGO_SVG_E_PNG.zip)
