### ISSUE TITLE
Logo do Projeto

### ISSUE THREAD

**Issue by BeyondMagic** [cerejeiros/mobile#2]
Aqui vocês podem postar logos, melhorar outras, e votar nas melhores.

Por favor postem os arquivos fontes das edições que vocês fizerem, por exemplo no Photoshop enviem a imagem e o arquivo .PSD, que é o que contém toda a edição em si para possível melhoramento por outra pessoa.

Vocês podem enviar versões anteriores.

**Comment by LeoFCastro** [comment]
![Image](https://user-images.githubusercontent.com/122454722/231031236-1e8c69e9-6e5a-478e-af3c-8bb1d6ef1312.png)

**Comment by BeyondMagic** [comment]
Idealização: para carregamento inicial do aplicativo logo na entrada, podemos ter a logo, em tese parecida com a pétala acima, caindo e girando no navigation bar (barra de baixo), logo ao centro; onde as abas do aplicativo ficarão ao lado.

**Comment by Neoprot** [comment]
![image](https://user-images.githubusercontent.com/119744000/231035345-20389925-bbb0-4fc2-85eb-9c1d091645b2.png)

**Comment by LeoFCastro** [comment]
![Image](https://user-images.githubusercontent.com/122454722/231039702-afccc1c5-9e49-466b-a4cc-1dbb1c0fb30e.png)

**Comment by Luizaxx** [comment]
![image](https://user-images.githubusercontent.com/122989271/231304097-23fea1e3-0165-442f-8b63-bc475b5432fe.png)
Oii galera, fiz algumas logos bem básicas baseadas nessa conversa acima, só para ter uma ideia do que a gente quer pro nosso projeto. Se vocês tiverem gostado de alguma poderíamos fazer uma votação e melhorar a mais votada se for preciso. Se não gostar de nenhuma, podemos ver mais inspirações.

**Comment by Luizaxx** [comment]
ah, todas estão no figma e todo mundo pode alterar o que achar necessário

**Comment by Luizaxx** [comment]
acho interessante essas que possuem sobreposição de cores porque dá a possibilidade de fazermos a logo em movimento quando o usuário entrar no aplicativo e aparecer a logo em movimento (junção das pétalas ou algo do tipo)

**Comment by LeoFCastro** [comment]
Gostei bastante da opção 5

**Comment by BeyondMagic** [comment]
As logos tem que ser um pouco mais simples  não tão moderno nesse sentido mas porque quando mudarmos a escala, ela tem que ficar tão boa e identificável quanto quando pequeno grande

**Comment by Luizaxx** [comment]
O que você acha da logo cinco na versão simplificado

**Comment by BeyondMagic** [comment]
Eu gostei da 3 e 5. A 3 tá perfeita para fazer em design grafico de vetor, a 5 precisa ter as linhas de centro maiores.

Se possível, amanhã ou hoje à noite vejo como ficaria no Inkscape.

**Comment by kaioenzo** [comment]
Eu voto na opção 2,3 e 5!

**Comment by limonadaquente** [comment]
Gostei principalmente da opção 3

**Comment by kaioenzo** [comment]
Por votação do grupo, a escolha da logo foi a logo 4.
