### ISSUE TITLE
fontes padrões 

### ISSUE THREAD

**Issue by NATANGOATOSO** [cerejeiros/mobile#23]
qual a fonte que será usado para a palavras do aplicativo:

**Comment by Neoprot** [comment]
# Precisamos de fonte que passem:
- Confiança e credibilidade;
- Criatividade;
- Leveza e tranquilidade

Ainda não sei, nem tenho uma ideia de qual usar, quando voltar pra casa hj estarei pesquisando e levarei as que eu achar interessante, também estarei lendo sobre oq casa tipo de fonte passa.

**Comment by BeyondMagic** [comment]
> # Precisamos de fonte que passem:
> - Confiança e credibilidade;
> - Criatividade;
> - Leveza e tranquilidade

Não, fonte não é uma paleta de cores. Os principais critérios são: nada muito diferente das fontes padrões de um celular (não pode ser Serif a não ser em partes especificas); confortável aos olhos (legibilidade); que tenha um alto suporte UTF-32 (nomes com caracteres especiais); suporte para um alto range de tamanhos; etc..., coisas bem mais objetivas.
 
Do próprio site que você linkou (inclusive acho que é uma tradução direta da seção de tipografia do material3):
- Convidar à leitura
- Revelar o teor do texto
- Tornar clara a estrutura (aprenda mais sobre hierarquia visual)
- Conectar o texto com outros elementos

**Comment by Luizaxx** [comment]
Montserrat e suas variações

**Comment by Luizaxx** [comment]
poppins

**Comment by Luizaxx** [comment]
inter

**Comment by BeyondMagic** [comment]
Comfortaa
https://fonts.google.com/specimen/Comfortaa?preview.text=Do+10+math+exercises+everyday&preview.text_type=custom&category=Display

**Comment by Neoprot** [comment]
Me expressei errado, quis dizer que precisávamos de uma fonte que passasse tudo isso, gostei tanto da Comfortaa quanto da Poppins, se fosse pra decidir pegaria uma das duas

**Comment by BeyondMagic** [comment]
https://docs.expo.dev/develop/user-interface/fonts/
