### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by kaioenzo** [cerejeiros/mobile#24]
# História de Usuário

Eu como usuário quero poder criar meus hábitos, escolher sua prioridade, escolher o horário específico que quero faze-la, e poder marcar quando cumprir esse hábito.

## Critérios de aceitação
- [ ] Criação de hábitos:
   - [ ] Atribuição de prioridade;
   - [ ] Escolha de horário específico no formato apropriado
   - [ ] Marcação de cumprido;

## Modelagem
```typescript
type Task = {
  name: string;
  id: number;
  priority?: 'urgent' | 'high' | 'medium' | 'low';
  status: 'done' | 'in progress' | 'disabled';
  createdTimeStamp: number;
  time: string;
  user: User;
  shared: boolean;
};
```

**Comment by BeyondMagic** [comment]
- [x] Implementação inicial em #40.
