### ISSUE TITLE
Paleta de Cores

### ISSUE THREAD

**Issue by BeyondMagic** [cerejeiros/mobile#3]
Aqui será discutido a paleta de cores do front-end (mobile).

Idealizado pela @limonadaquente, a paleta de cores poderia ser inspirado pelo o nome do grupo, "flor de cerejeira".

As cores serão testadas no https://www.figma.com/ com o intuito de ter uma melhor ideia de como elas poderiam ser aplicadas no design.

**Comment by BeyondMagic** [comment]
Baseando-se na flor de cerejeira, para um tema claro as seguintes cores poderiam ser usadas:

![image](https://user-images.githubusercontent.com/51831435/231024477-5a39baea-faec-47bd-849d-766eb000697e.png)

Possuem alto contraste (são cores fortes), então o ideal é utilizar cores mais cinzas para diferentes seções do aplicativo.

**Comment by BeyondMagic** [comment]
Indo à direção oposta, cores mais relaxadas como o azul entram no padrão moderno de aplicativo do dia a dia.

![image](https://user-images.githubusercontent.com/51831435/231025201-b35f2be7-c5f0-4731-8710-3ea78bd7b924.png)

**Comment by Luizaxx** [comment]
Paleta de cores que em tese seguiria a paleta de cores idealizada de inicio, mas adicionando o tom de azul e um semelhante a um cinza para títulos. 


![Image](https://user-images.githubusercontent.com/122989271/231027724-c0f42e34-f28b-494c-804a-7e65082fb8e6.png)

**Comment by NATANGOATOSO** [comment]
![Image](https://user-images.githubusercontent.com/61543235/231029154-ba958228-97cd-49ab-89e3-b5f669e6d5b1.png)

**Comment by NATANGOATOSO** [comment]
![image](https://user-images.githubusercontent.com/61543235/231492843-0dc24e8d-9630-4359-a165-c393b15bce51.jpeg)

Para o modo escuro

**Comment by BeyondMagic** [comment]
> Paleta de cores que em tese seguiria a paleta de cores idealizada de inicio, mas adicionando o tom de azul e um semelhante a um cinza para títulos.
> 
> ![image](https://user-images.githubusercontent.com/51831435/231028221-e8a8cbee-e05f-4c49-bd9f-83983e841f3e.png)

Paleta principal definida.

Paleta secundária (para tema escuro e afins) a gente pode ir discutindo com o tempo.

Essa feita pelo @NATANGOATOSO já pode ser algo inicial.
